### PR TITLE
update to rustc nightly 2018-03-07

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request does the every-two-month update to rustc. Not too much exciting, but did have to add a new feature declaration.

I did want to include some errors that adding `#![feature(ptr_internals)]` avoided in case the suggestions are actually worth us looking into:

```
error[E0658]: use of unstable library feature 'ptr_internals': use NonNull instead and consider PhantomData<T> (if you also use #[may_dangle]), Send, and/or Sync (see issue #0)
 --> /Users/bradjc/git/tock/kernel/src/grant.rs:7:48
  |
7 | use core::ptr::{read_volatile, write_volatile, Unique};
  |                                                ^^^^^^
  |
  = help: add #![feature(ptr_internals)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'ptr_internals': use NonNull instead and consider PhantomData<T> (if you also use #[may_dangle]), Send, and/or Sync (see issue #0)
  --> /Users/bradjc/git/tock/kernel/src/grant.rs:52:11
   |
52 |     data: Unique<T>,
   |           ^^^^^^^^^
   |
   = help: add #![feature(ptr_internals)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'ptr_internals': use NonNull instead and consider PhantomData<T> (if you also use #[may_dangle]), Send, and/or Sync (see issue #0)
 --> /Users/bradjc/git/tock/kernel/src/mem.rs:6:5
  |
6 | use core::ptr::Unique;
  |     ^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(ptr_internals)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'ptr_internals': use NonNull instead and consider PhantomData<T> (if you also use #[may_dangle]), Send, and/or Sync (see issue #0)
  --> /Users/bradjc/git/tock/kernel/src/mem.rs:16:10
   |
16 |     ptr: Unique<T>,
   |          ^^^^^^^^^
   |
   = help: add #![feature(ptr_internals)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'ptr_internals': use NonNull instead and consider PhantomData<T> (if you also use #[may_dangle]), Send, and/or Sync (see issue #0)
  --> /Users/bradjc/git/tock/kernel/src/grant.rs:59:19
   |
59 |             data: Unique::new_unchecked(data),
   |                   ^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(ptr_internals)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'ptr_internals': use NonNull instead and consider PhantomData<T> (if you also use #[may_dangle]), Send, and/or Sync (see issue #0)
  --> /Users/bradjc/git/tock/kernel/src/mem.rs:24:18
   |
24 |             ptr: Unique::new_unchecked(ptr),
   |                  ^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(ptr_internals)] to the crate attributes to enable
```

There are also a couple warnings that will go away when the sam4l usart to new regs is merged.

### Testing Strategy

This pull request was tested by running some apps on hail.

### TODO or Help Wanted

This pull request still needs...

### Documentation Updated

- [x] Kernel: Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by bradjc** [comment]
Unfortunately also had to update rustfmt because version 0.3.4 won't compile with rust nightly 1.26. I chose to do the smallest update that allows it to compile to minimize the amount of source formatting changes (hence the bump to 0.3.5).

**Comment by alevy** [comment]
`NotNull` seems very new. I can't say that I totally understand the differences with `Unique` nor can I find a deprecation notice/explanation in the nightly docs. I think it's totally safe to keep these for this upgrade, but we might end up switching if `Unique` gets totally removed or if we realize there is a better way.

File: tools/install_cargo_fmt.sh [hunk 1]
```diff
@@ -15,7 +15,7 @@ fi
 #
 # Note: We install a local copy of rustfmt so as not to interfere with any
 # other use of rustfmt on the machine
-RUSTFMT_VERSION=0.3.4
+RUSTFMT_VERSION=0.3.5
 
 if [[ $(rustc --version) != "rustc 1.24.0-nightly (8e7a609e6 2018-01-04)" ]]; then
```
Comment (ppannuto) [inline tools/install_cargo_fmt.sh]: Missed this the first time around, but shouldn't line have updated too?
